Add the settings_file param

diff --git a/src/commands/deploy-or-update.yml b/src/commands/deploy-or-update.yml
--- a/src/commands/deploy-or-update.yml
+++ b/src/commands/deploy-or-update.yml
@@ -2,6 +2,16 @@ description: >
   Update an existing Zappa stage or deploy a new one.
 
 parameters:
+  all_stages:
+    type: boolean
+    default: false
+    description: >
+      Whether to deploy to all stages in the settings file.
+  settings_file:
+    type: string
+    default: "zappa_settings.json"
+    description: >
+      The path to the zappa settings file.
   stage:
     type: string
     default: "dev"
@@ -9,15 +19,52 @@ parameters:
       The name of the Zappa stage to update or deploy to.
 
 steps:
-  - run:
-      name: Deploying to << parameters.stage >>
-      command: |-
-        set +e
-        STATUS=$(pipenv run zappa status << parameters.stage >> -j 2>&1)
-        set -e
-        if [[ $(echo $STATUS | jq . 2>/dev/null) ]];
-        then pipenv run zappa update << parameters.stage >>;
-        elif [[ "$STATUS" == *"have you deployed yet?" ]];
-        then pipenv run zappa deploy << parameters.stage >>;
-        else echo "$STATUS\nUnknown error!" && exit 1
-        fi
+  - unless:
+      condition: << parameters.all_stages >>
+      steps:
+        - run:
+            name: Deploying to << parameters.stage >>
+            command: |-
+              set +e
+              SETTINGS="--settings_file << parameters.settings_file >>"
+              STATUS=$(pipenv run zappa status << parameters.stage >> --json $SETTINGS 2>&1)
+              set -e
+              if [[ $(echo $STATUS | jq . 2>/dev/null) ]];
+              then pipenv run zappa update << parameters.stage >> $SETTINGS;
+              elif [[ "$STATUS" == *"have you deployed yet?" ]];
+              then pipenv run zappa deploy << parameters.stage >> $SETTINGS;
+              else echo "$STATUS\nUnknown error!" && exit 1
+              fi
+
+  - when:
+      condition: << parameters.all_stages >>
+      steps:
+        - run:
+            name: Deploying to all stages
+            command: |-
+              set +e
+              SETTINGS="--settings_file << parameters.settings_file >>"
+              STATUS=$(pipenv run zappa status --all --json $SETTINGS 2>&1 >/dev/null)
+              ALL_DEPLOYMENTS=$(cat << parameters.settings_file >> | jq -r '. | keys | join(" ")')
+              NEW_DEPLOYMENTS=$(echo $STATUS | awk '{
+                if ( length($0)!=0 && $0 '\!'~ /^Error: No Lambda.*deployed/ ) {
+                  exit 1
+                }
+                else print $4
+              }')
+              STATUS_EXIT_CODE=$?
+              NEW_DEPLOYMENT_COUNT=$(echo $NEW_DEPLOYMENTS | wc -w)
+              TOTAL_DEPLOYMENT_COUNT=$(echo $ALL_DEPLOYMENTS | wc -w)
+              set -e
+              if [[ "$STATUS_EXIT_CODE" != "0" ]]
+                then echo "$STATUS\nUnknown error!" && exit 1
+              elif [[ "$NEW_DEPLOYMENT_COUNT" == "$TOTAL_DEPLOYMENT_COUNT" ]]
+                then pipenv run zappa deploy --all $SETTINGS
+              elif [ "$NEW_DEPLOYMENT_COUNT" -gt "0" ]
+                then for DEPLOYMENT_NAME in $NEW_DEPLOYMENTS
+                  do
+                  STAGE=$(echo $DEPLOYMENT_NAME | awk -F- '{print $NF}')
+                  pipenv run zappa deploy $STAGE $SETTINGS
+                done
+              fi
+              pipenv run zappa update --all $SETTINGS
