shell script fixes

diff --git a/src/commands/deploy-or-update.yml b/src/commands/deploy-or-update.yml
--- a/src/commands/deploy-or-update.yml
+++ b/src/commands/deploy-or-update.yml
@@ -49,10 +49,10 @@ steps:
               NEW_DEPLOYMENT_COUNT=$(echo $NEW_DEPLOYMENTS | wc -w)
               TOTAL_DEPLOYMENT_COUNT=$(echo $ALL_DEPLOYMENTS | wc -w)
               set -e
-              if [[ "$STATUS_EXIT_CODE" != "0" ]] then
-                echo "$STATUS\nUnknown error!" && exit 1
-              elif [[ "$NEW_DEPLOYMENT_COUNT" == "$TOTAL_DEPLOYMENT_COUNT" ]] then
-                pipenv run zappa deploy --all
+              if [[ "$STATUS_EXIT_CODE" != "0" ]]
+                then echo "$STATUS\nUnknown error!" && exit 1
+              elif [[ "$NEW_DEPLOYMENT_COUNT" == "$TOTAL_DEPLOYMENT_COUNT" ]]
+                then pipenv run zappa deploy --all
               elif [ "$NEW_DEPLOYMENT_COUNT" -gt "0" ]
                 for DEPLOYMENT_NAME in $NEW_DEPLOYMENTS do
                   STAGE=$(echo $DEPLOYMENT_NAME | awk -F- '{print $NF}')
